### Adding Event
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "title": "Lection",
  "date": "2023-10-15"
}

### Adding Site to Event
POST http://localhost:8080/api/events/1/sites/1
Content-Type: application/json

{
}

### Adding Site
POST http://localhost:8080/api/sites
Content-Type: application/json

{
  "name": "Theater Opera4"
}
###Add New participant

POST localhost:8080/api/participants/register
Content-Type: application/json

{
  "name": "NewParticipantName1",
  "email": "newuser1@gmail.com"
}

### Add participants to the event

POST localhost:8080/api/events/2/participant
Content-Type: application/json

{
  "participantId": 1
}

###

