### Adding Event
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "title": "Lection2",
  "date": "2023-10-15"
}

### Adding Site to Event
POST http://localhost:8080/api/events/1/sites/1
Content-Type: application/json


### Adding Site
POST http://localhost:8080/api/sites
Content-Type: application/json

{
  "name": "Theater Opera5"
}
###Add New participant

POST localhost:8080/api/participants/register
Content-Type: application/json

{
  "name": "NewParticipantName2",
  "email": "newuser2@gmail.com",
  "password": "Qwerty007!"
}

### Add participant to the event

POST localhost:8080/api/events/2/participant
Content-Type: application/json

{
  "participantId": 1
}

### Get participants of Event

GET localhost:8080/api/events/2/participants

### Update Event
PUT localhost:8080/api/events/1
Content-Type: application/json

{
"title": "Songs and dance2",
"data": "2023-11-26",
"site": 1
}

### Delete the event

DELETE localhost:8080/api/sites/1

###

95fba71e-3cb0-4716-aca1-179c4d02819f


